spring.application.name=Farme_rich
server.port=8081
#spring.application.name=fr_dev
spring.data.mongodb.uri=mongodb://localhost:27017/Clothes
#spring.data.mongodb.uri=mongodb://HandsomeKing1:FireAnt456%24%21@13.203.221.169:27017/fr?authSource=fr&replicaSet=rs0&directConnection=true
#spring.data.mongodb.uri=mongodb://testuser:testpwd@13.203.221.169:27017/fr_dev?authSource=fr_dev&replicaSet=rs0&directConnection=true
#spring.data.mongodb.uri=mongodb://HandsomeKing1:FireAnt456$!@13.203.221.169:27017/fr?authSource=fr&replicaSet=rs0&directConnection=true
app.upload-dir=uploads/
#
#---------------AWS
#app.baseUrl=https://dev.fr.api.intellesyde.com
#app.Ec2BaseUrl=https://inock.intellesyde.com
#app.SuggestUrl=https://dev.fr.api.intellesyde.com
#app.image-storage-path=https://inock.intellesyde.com/uploads
#app.ImgUrl=https://inock.intellesyde.com
#
#---------------Local
app.baseUrl=http://192.168.1.7:8080
app.Ec2BaseUrl=http://192.168.1.7:8080
app.SuggestUrl=http://192.168.1.7:8080
app.image-storage-path=http://192.168.1.7:8080/uploads
app.ImgUrl=http://192.168.1.7:8080
#
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#*********yogesh gmail start*********
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yogeshgimmy07@gmail.com
spring.mail.password=hkndcgxypiugdxse
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#*********yogesh gmail end*********
#*********office mail start*********
#spring.mail.host=smtp.office365.com
#spring.mail.port=587
#spring.mail.username=admin@intellesyde.com
#spring.mail.password=gpfhnqflnjsfbcdx
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#*********office mail end*********
whatsapp.phoneID=1120745707799676
whatsapp.token=EAAYWAoLBq4YBSgxKB80EkAw9VOrDyhnSVtsB78GC4ZB4QMDyBl5qheUdrEHx9cIy0RtJuBmuObssvZBIn9vHIWRjw39DJgKWVYSOlooc7xZC3HTbd33MZBh1NGFpGIYrpSlInxgfgRUB7m0cOZCWdIzmAfvdh5QdUcCRbarZB47ziDDjoBwKH9I56wvYqJ9buvYZC3mwC4h1iPYQYComqVGouNmVdg1I8wALteY